# Generated by Django 5.1.1 on 2024-11-22 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseid', models.AutoField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=255)),
                ('coursecode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('categoryid', models.AutoField(primary_key=True, serialize=False)),
                ('categoryname', models.CharField(max_length=255, unique=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resourceid', models.AutoField(primary_key=True, serialize=False)),
                ('resourcename', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('availability', models.BooleanField(default=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('resource_type', models.CharField(choices=[('public', 'Public'), ('borrowed', 'Borrowed')], default='borrowed', max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.resourcecategory')),
                ('lender', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resources_lent', to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='resource_images/')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.resource')),
            ],
        ),
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('lenderid', models.AutoField(primary_key=True, serialize=False)),
                ('lendingdate', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.resourcecategory')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lended_resources', to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedbackid', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.resource')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('borrowingid', models.AutoField(primary_key=True, serialize=False)),
                ('borrowdate', models.DateField()),
                ('returndate', models.DateField()),
                ('status', models.CharField(default='borrowed', max_length=50)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.resource')),
                ('borrower', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_resources', to='core.user')),
            ],
        ),
    ]
