# Generated by Django 5.1.1 on 2024-11-25 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_is_active_user_is_admin_user_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_resources', to='core.user'),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='status',
            field=models.CharField(choices=[('borrowed', 'Borrowed'), ('returned', 'Returned')], default='borrowed', max_length=50),
        ),
        migrations.AlterField(
            model_name='lender',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lended_resources', to='core.user'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='lender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources_lent', to='core.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
