# Generated by Django 5.1.1 on 2024-11-25 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lender',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lended_resources', to=settings.AUTH_USER_MODEL),
        ),
    ]
