# Generated by Django 5.1.1 on 2024-11-25 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_lender_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources_lent', to=settings.AUTH_USER_MODEL),
        ),
    ]
