# Generated by Django 5.1.1 on 2024-11-25 13:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_resource_lender'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
