# Generated by Django 5.1.1 on 2024-11-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_resource_uploaded_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
